### ISSUE TITLE
Run Benchmark for IMI and Record Resource Utilization

### ISSUE THREAD

**Issue by ddalton-swe** [JPL-MGHG/JPL-MGHG-SDS#35]

**Comment by ddalton-swe** [comment]
Here is what the run looked like on MAAP before the job crashed:

![Image](https://github.com/JPL-MGHG/JPL-MGHG-SDS/assets/103046626/a48eb588-e859-4db5-a848-2b268ab70277)

**Comment by ddalton-jpl** [comment]
We can see here that IMI makes use of all of the cores available to it. The current instance size that is used by IMI is c5.9xlarge

**Comment by ddalton-swe** [comment]
You can set the resource utilization using the container_config.yml file. The default is 16 cores with 16GB of RAM
